app/Http/routes.php
<?php

	Route::group(['middleware' => 'web'], function () {
	Route::get('login', 'Auth\AuthController@getLogin');
	Route::post('login', 'Auth\AuthController@postLogin');

	Route::get('logout', [
		'as' => 'auth.logout',
		'uses' => 'Auth\AuthController@getLogout',
	]);

	if (settings('reg_enabled')) {
		Route::get('register', 'Auth\AuthController@getRegister');
		Route::post('register', 'Auth\AuthController@postRegister');
		Route::get('register/confirmation/{token}', [
			'as' => 'register.confirm-email',
			'uses' => 'Auth\AuthController@confirmEmail',
		]);
	}

	if (settings('forgot_password')) {
		Route::get('password/remind', 'Auth\PasswordController@forgotPassword');
		Route::post('password/remind', 'Auth\PasswordController@sendPasswordReminder');
		Route::get('password/reset/{token}', 'Auth\PasswordController@getReset');
		Route::post('password/reset', 'Auth\PasswordController@postReset');
	}

	if (settings('2fa.enabled')) {
		Route::get('auth/two-factor-authentication', [
			'as' => 'auth.token',
			'uses' => 'Auth\AuthController@getToken',
		]);

		Route::post('auth/two-factor-authentication', [
			'as' => 'auth.token.validate',
			'uses' => 'Auth\AuthController@postToken',
		]);
	}

	Route::get('auth/{provider}/login', [
		'as' => 'social.login',
		'uses' => 'Auth\SocialAuthController@redirectToProvider',
		'middleware' => 'social.login',
	]);

	Route::get('auth/{provider}/callback', 'Auth\SocialAuthController@handleProviderCallback');

	Route::get('auth/twitter/email', 'Auth\SocialAuthController@getTwitterEmail');
	Route::post('auth/twitter/email', 'Auth\SocialAuthController@postTwitterEmail');

});

Route::group(['middleware' => 'web'], function () {
	Route::localizedGroup(function () {
		//CMS
		Route::get('/', 'Frontend\HomeController@home')->name('frontend.index');
		Route::get('/faq', 'Frontend\PageController@faq')->name('frontend.faq');
		Route::get('/policy', 'Frontend\PageController@privacyPolicy')->name('frontend.privacyPolicy');
		Route::get('/partner-with-us', 'Frontend\PageController@partner')->name('frontend.partner');
		Route::get('/about-us', 'Frontend\PageController@about')->name('frontend.about');
    Route::get('/terms-and-conditions', 'Frontend\PageController@terms')->name('frontend.terms');
    Route::get('/careers', 'Frontend\PageController@careers')->name('frontend.careers');
    Route::get('/blogs', 'Frontend\PageController@blog')->name('frontend.blog');
    Route::get('/blog/{id}', 'Frontend\PageController@blogDetail')->name('frontend.blogDetail');
		Route::get('/contact-us', 'Frontend\PageController@contact')->name('frontend.contact');
		Route::post('/contact-us', 'Frontend\PageController@contactPost')->name('frontend.contactPost');
		//CMS end
		Route::group(['namespace' => 'Dashboard', 'prefix' => 'dashboard'], function () {
			Route::get('/', [
				'as' => 'dashboard',
				'uses' => 'DashboardController@index',
			]);
			/*
			*
			* gokul working currentily
			*
			*/


      Route::resource('cms', 'CmsController');
      Route::resource('faq', 'FaqController');
      Route::resource('jobs', 'JobController');
      Route::resource('blogs', 'BlogController');
			/*
			*
			* gokul working currentily
			*
			*/
			Route::get('profile', [
				'as' => 'profile',
				'uses' => 'ProfileController@index',
			]);

			Route::get('profile/activity', [
				'as' => 'profile.activity',
				'uses' => 'ProfileController@activity',
			]);

			Route::put('profile/details/update', [
				'as' => 'profile.update.details',
				'uses' => 'ProfileController@updateDetails',
			]);

			Route::post('profile/avatar/update', [
				'as' => 'profile.update.avatar',
				'uses' => 'ProfileController@updateAvatar',
			]);

			Route::post('profile/avatar/update/external', [
				'as' => 'profile.update.avatar-external',
				'uses' => 'ProfileController@updateAvatarExternal',
			]);

			Route::put('profile/login-details/update', [
				'as' => 'profile.update.login-details',
				'uses' => 'ProfileController@updateLoginDetails',
			]);

			Route::put('profile/social-networks/update', [
				'as' => 'profile.update.social-networks',
				'uses' => 'ProfileController@updateSocialNetworks',
			]);

			Route::post('profile/two-factor/enable', [
				'as' => 'profile.two-factor.enable',
				'uses' => 'ProfileController@enableTwoFactorAuth',
			]);

			Route::post('profile/two-factor/disable', [
				'as' => 'profile.two-factor.disable',
				'uses' => 'ProfileController@disableTwoFactorAuth',
			]);

			Route::get('profile/sessions', [
				'as' => 'profile.sessions',
				'uses' => 'ProfileController@sessions',
			]);

			Route::delete('profile/sessions/{session}/invalidate', [
				'as' => 'profile.sessions.invalidate',
				'uses' => 'ProfileController@invalidateSession',
			]);

			Route::get('user', [
				'as' => 'user.list',
				'uses' => 'UsersController@index',
			]);

			Route::get('user/create', [
				'as' => 'user.create',
				'uses' => 'UsersController@create',
			]);

			Route::post('user/create', [
				'as' => 'user.store',
				'uses' => 'UsersController@store',
			]);

			Route::get('user/{user}/show', [
				'as' => 'user.show',
				'uses' => 'UsersController@view',
			]);

			Route::get('user/{user}/edit', [
				'as' => 'user.edit',
				'uses' => 'UsersController@edit',
			]);

			Route::put('user/{user}/update/details', [
				'as' => 'user.update.details',
				'uses' => 'UsersController@updateDetails',
			]);

			Route::put('user/{user}/update/login-details', [
				'as' => 'user.update.login-details',
				'uses' => 'UsersController@updateLoginDetails',
			]);

			Route::delete('user/{user}/delete', [
				'as' => 'user.delete',
				'uses' => 'UsersController@delete',
			]);

			Route::post('user/{user}/update/avatar', [
				'as' => 'user.update.avatar',
				'uses' => 'UsersController@updateAvatar',
			]);

			Route::post('user/{user}/update/avatar/external', [
				'as' => 'user.update.avatar.external',
				'uses' => 'UsersController@updateAvatarExternal',
			]);

			Route::post('user/{user}/update/social-networks', [
				'as' => 'user.update.socials',
				'uses' => 'UsersController@updateSocialNetworks',
			]);

			Route::get('user/{user}/sessions', [
				'as' => 'user.sessions',
				'uses' => 'UsersController@sessions',
			]);

			Route::delete('user/{user}/sessions/{session}/invalidate', [
				'as' => 'user.sessions.invalidate',
				'uses' => 'UsersController@invalidateSession',
			]);

			Route::post('user/{user}/two-factor/enable', [
				'as' => 'user.two-factor.enable',
				'uses' => 'UsersController@enableTwoFactorAuth',
			]);

			Route::post('user/{user}/two-factor/disable', [
				'as' => 'user.two-factor.disable',
				'uses' => 'UsersController@disableTwoFactorAuth',
			]);

			Route::get('role', [
				'as' => 'role.index',
				'uses' => 'RolesController@index',
			]);

			Route::get('role/create', [
				'as' => 'role.create',
				'uses' => 'RolesController@create',
			]);

			Route::post('role/store', [
				'as' => 'role.store',
				'uses' => 'RolesController@store',
			]);

			Route::get('role/{role}/edit', [
				'as' => 'role.edit',
				'uses' => 'RolesController@edit',
			]);

			Route::put('role/{role}/update', [
				'as' => 'role.update',
				'uses' => 'RolesController@update',
			]);

			Route::delete('role/{role}/delete', [
				'as' => 'role.delete',
				'uses' => 'RolesController@delete',
			]);

			Route::post('permission/save', [
				'as' => 'dashboard.permission.save',
				'uses' => 'PermissionsController@saveRolePermissions',
			]);

			Route::resource('permission', 'PermissionsController');

			Route::get('settings', [
				'as' => 'settings.general',
				'uses' => 'SettingsController@general',
				'middleware' => 'permission:settings.general',
			]);

			Route::post('settings/general', [
				'as' => 'settings.general.update',
				'uses' => 'SettingsController@update',
				'middleware' => 'permission:settings.general',
			]);

			Route::get('settings/auth', [
				'as' => 'settings.auth',
				'uses' => 'SettingsController@auth',
				'middleware' => 'permission:settings.auth',
			]);

			Route::post('settings/auth', [
				'as' => 'settings.auth.update',
				'uses' => 'SettingsController@update',
				'middleware' => 'permission:settings.auth',
			]);

			if (env('AUTHY_KEY')) {
				Route::post('settings/auth/2fa/enable', [
					'as' => 'settings.auth.2fa.enable',
					'uses' => 'SettingsController@enableTwoFactor',
					'middleware' => 'permission:settings.auth',
				]);

				Route::post('settings/auth/2fa/disable', [
					'as' => 'settings.auth.2fa.disable',
					'uses' => 'SettingsController@disableTwoFactor',
					'middleware' => 'permission:settings.auth',
				]);
			}

			Route::post('settings/auth/registration/captcha/enable', [
				'as' => 'settings.registration.captcha.enable',
				'uses' => 'SettingsController@enableCaptcha',
				'middleware' => 'permission:settings.auth',
			]);

			Route::post('settings/auth/registration/captcha/disable', [
				'as' => 'settings.registration.captcha.disable',
				'uses' => 'SettingsController@disableCaptcha',
				'middleware' => 'permission:settings.auth',
			]);

			Route::get('settings/notifications', [
				'as' => 'settings.notifications',
				'uses' => 'SettingsController@notifications',
				'middleware' => 'permission:settings.notifications',
			]);

			Route::post('settings/notifications', [
				'as' => 'settings.notifications.update',
				'uses' => 'SettingsController@update',
				'middleware' => 'permission:settings.notifications',
			]);

			Route::get('activity', [
				'as' => 'activity.index',
				'uses' => 'ActivityController@index',
			]);

			Route::get('activity/user/{user}/log', [
				'as' => 'activity.user',
				'uses' => 'ActivityController@userActivity',
			]);

			Route::group([
				'prefix' => 'log-viewer',
				'middleware' => 'role:Admin',
			], function () {
				Route::get('/', [
					'as' => 'log-viewer::dashboard',
					'uses' => '\Arcanedev\LogViewer\Http\Controllers\LogViewerController@index',
				]);

app/Cms.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Cms extends Model
{
     protected $table = 'cms';
}

app/Http/Controllers/Dashboard/ActivityController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Repositories\Activity\ActivityRepository;
use App\User;
use Illuminate\Http\Request;

/**
 * Class ActivityController
 * @package App\Http\Controllers
 */
class ActivityController extends Controller {
	/**
	 * @var EloquentActivity
	 */
	private $activities;

	/**
	 * ActivityController constructor.
	 * @param ActivityRepository $activities
	 */
	public function __construct(ActivityRepository $activities) {
		$this->middleware('permission:users.activity');
		$this->activities = $activities;
	}

	/**
	 * Displays the page with activities for all system users.
	 *
	 * @param Request $request
	 * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
	 */
	public function index(Request $request) {
		$perPage = 20;
		$adminView = true;

		$activities = $this->activities->paginateActivities($perPage, $request->get('search'));

		return view('dashboard.activity.index', compact('activities', 'adminView'));
	}

	/**
	 * Displays the activity log page for specific user.
	 *
	 * @param User $user
	 * @param Request $request
	 * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
	 */
	public function userActivity(User $user, Request $request) {
		$perPage = 20;
		$adminView = true;

		$activities = $this->activities->paginateActivitiesForUser(
			$user->id, $perPage, $request->get('search')
		);

		return view('dashboard.activity.index', compact('activities', 'user', 'adminView'));
	}
}

app/Http/Controllers/Dashboard/BlogController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use App\Blogs as BlogModel;
use Illuminate\Support\Facades\Input as Input ;
use Illuminate\Support\Facades\Storage as Storage ;
use Illuminate\Support\Facades\File as File ;
use App\User;
use Auth;
use App\Repositories\User\UserRepository;
use Illuminate\Validation\Validator as Validator;
use Illuminate\Foundation\Validation\ValidatesRequests;

/**
 * Class BlogController
 * @package App\Http\Controllers
 */
class BlogController extends Controller {


	/**
	 * UsersController constructor.
	 * @param UserRepository $users
	 */
	public function __construct(UserRepository $users) {
		$this->middleware('auth');
		$this->middleware('session.database', ['only' => ['sessions', 'invalidateSession']]);
		$this->middleware('permission:users.manage');
		$this->users = $users;
	}

	/**
	 * Displays the page with all available Blogs
	 *
	 * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
	 */
	public function index() {
		$blogs=BlogModel::all();

		return view('dashboard.cms.blog.index', compact('blogs'));
	}

	/**
	 * Displays the form for creating new Opening.
	 *
	 * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
	 */
	public function create() {
		$edit = false;

		return view('dashboard.cms.blog.add-edit', compact('edit'));
	}

	/**
	 * Store Blog to database and image file to upload folder
	 *
	 * @return mixed
	 */
	public function store() {
		$input = Input::all();
		$table = new BlogModel;
	  if (Input::hasFile('image'))
		 {
			 $destinationPath="upload/blogs";	 // upload path
			 $extension = Input::file('image')->getClientOriginalExtension(); // getting image extension
       $fileName = rand(11111,99999).'.'.$extension; // renameing image
       Input::file('image')->move($destinationPath, $fileName);
			 $table->image=$fileName;
		 }
		$table->title  = $input['title'];
		$table->contents = $input['Content'];
		$table->save();
		return redirect()->route('dashboard.blogs.index')
			->withSuccess('New Blog added Successfully');
	}

	/**
	 * Displays the form for editing specific Blog.
	 *
	 * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
	 */
	public function edit( $id) {
		$edit = true;
		$blog=BlogModel::find($id);
		return view('dashboard.cms.blog.add-edit', compact('edit', 'blog'));
	}

	/**
	 * Update specified Blog.
	 *
	 * @return mixed
	 */
	public function update($id) {
		$input = Input::all();
		$table = BlogModel::findOrFail($id);
		// echo $table->image; die;
		if (Input::hasFile('image'))
		 {
			 File::delete('upload/blogs/'.$table->image); //delete current file
			//  Storage::delete('upload/blogs/123.jpg'); //delete current file

			 $destinationPath="upload/blogs";	 // upload path
			 $extension = Input::file('image')->getClientOriginalExtension(); // getting image extension
       $fileName = rand(11111,99999).'.'.$extension; // renameing image
       Input::file('image')->move($destinationPath, $fileName);
			 $table->image=$fileName;
		 }
		$table->title = $input['title'];
		$table->contents = $input['Content'];
		$table->save();

		// File::delete($filename);
		return redirect()->route('dashboard.blogs.index')
			->withSuccess('Blog Updated Successfully');
	}

	/**
	 * Destroy the Blog.
	 *
	 * @return mixed
	 * @throws \Exception
	 */
	public function destroy($id) {
		$table = BlogModel::findOrFail($id);

		File::delete('upload/blogs/'.$table->image);
		BlogModel::destroy($id);

		return redirect()->route('dashboard.blogs.index')
			->withSuccess('Blog deleted successfully');
	}

}

app/Http/Controllers/Dashboard/DashboardController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Repositories\Activity\ActivityRepository;
use App\Repositories\User\UserRepository;
use App\Support\Enum\UserStatus;
use Auth;
use Carbon\Carbon;

class DashboardController extends Controller {
	/**
	 * @var UserRepository
	 */
	private $users;
	/**
	 * @var ActivityRepository
	 */
	private $activities;

	/**
	 * DashboardController constructor.
	 * @param UserRepository $users
	 * @param ActivityRepository $activities
	 */
	public function __construct(UserRepository $users, ActivityRepository $activities) {
		$this->middleware('auth');
		$this->users = $users;
		$this->activities = $activities;
	}

	/**
	 * Displays dashboard based on user's role.
	 *
	 * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
	 */
	public function index() {
		if (Auth::user()->hasRole('Admin')) {
			return $this->adminDashboard();
		}

		return $this->defaultDashboard();
	}

	/**
	 * Displays dashboard for admin users.
	 *
	 * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
	 */
	private function adminDashboard() {
		$usersPerMonth = $this->users->countOfNewUsersPerMonth(
			Carbon::now()->startOfYear(),
			Carbon::now()
		);

		$stats = [
			'total' => $this->users->count(),
			'new' => $this->users->newUsersCount(),
			'banned' => $this->users->countByStatus(UserStatus::BANNED),
			'unconfirmed' => $this->users->countByStatus(UserStatus::UNCONFIRMED),
		];

		$latestRegistrations = $this->users->latest(8);

		return view('dashboard.admin', compact('stats', 'latestRegistrations', 'usersPerMonth'));
	}

	/**
	 * Displays default dashboard for non-admin users.
	 *
	 * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
	 */
	private function defaultDashboard() {
		$activities = $this->activities->userActivityForPeriod(
			Auth::user()->id,
			Carbon::now()->subWeeks(2),
			Carbon::now()
		)->toArray();

		return view('dashboard.default', compact('activities'));
	}

}

resources/views/dashboard/cms/add-edit.blade.php
@extends('dashboard.layouts.master')

@section('page-title', trans('app.permissions'))

@section('page-header')
    <h1>
        {{ $edit ? $page->name : "New Page" }}
      </h1>
    <ol class="breadcrumb">
        <li><a href="{{ route('dashboard') }}"><i class="fa fa-dashboard"></i> @lang('app.home')</a></li>
        <li><a href="{{ route('dashboard.cms.index') }}">CMS</a></li>
        <li class="active">{{ $edit ? trans('app.edit') : trans('app.create') }}</li>
      </ol>
@endsection

@section('content')


@include('partials.messages')

@if ($edit)
    {!! Form::open(['route' => ['dashboard.permission.update', $permission->id], 'method' => 'PUT', 'id' => 'permission-form']) !!}
@else
    {!! Form::open(['route' => 'dashboard.permission.store', 'id' => 'permission-form']) !!}
@endif

<div class="row">
    <div class="col-lg-6 col-md-12 col-sm-12">
        <div class="panel panel-default">
            <div class="panel-heading">@lang('app.permission_details')</div>
            <div class="panel-body">
                <div class="form-group">
                    <label for="name">@lang('app.name')</label>
                    <input type="text" class="form-control" id="name"
                           name="name" placeholder="@lang('app.permission_name')" value="{{ $edit ? $permission->name : old('name') }}">
                </div>
                <div class="form-group">
                    <label for="display_name">@lang('app.display_name')</label>
                    <input type="text" class="form-control" id="display_name"
                           name="display_name" placeholder="@lang('app.display_name')" value="{{ $edit ? $permission->display_name : old('display_name') }}">
                </div>
                <div class="form-group">
                    <label for="description">@lang('app.description')</label>
                    <textarea name="description" id="description" class="form-control">{{ $edit ? $permission->description : old('description') }}</textarea>
                </div>
                </div>
            </div>
        </div>
    </div>

<div class="row">
    <div class="col-md-2">
        <button type="submit" class="btn btn-primary">
            <i class="fa fa-save"></i>
            {{ $edit ? trans('app.update_permission') : trans('app.create_permission') }}
        </button>
    </div>
</div>

@stop

@section('fter-scripts-end')
    @if ($edit)
        {!! JsValidator::formRequest('App\Http\Requests\Permission\UpdatePermissionRequest', '#permission-form') !!}
    @else
        {!! JsValidator::formRequest('App\Http\Requests\Permission\CreatePermissionRequest', '#permission-form') !!}
    @endif
@stop

resources/views/dashboard/cms/edit.blade.php
@extends('dashboard.layouts.master')
<script src="//cdn.tinymce.com/4/tinymce.min.js"></script>
<script>tinymce.init({ selector:'textarea' });</script>

@section('page-title', trans('app.permissions'))

@section('page-header')
    <h1>
        {{ $edit ? $page->page : "New Page" }}
      </h1>
    <ol class="breadcrumb">
        <li><a href="{{ route('dashboard') }}"><i class="fa fa-dashboard"></i> @lang('app.home')</a></li>
        <li><a href="{{ route('dashboard.cms.index') }}">CMS</a></li>
        <li class="active">{{ $edit ? trans('app.edit') : trans('app.create') }}</li>
      </ol>
@endsection

@section('content')


@include('partials.messages')

    {!! Form::open(['route' => ['dashboard.cms.update', $page->id], 'method' => 'PUT', 'id' => 'permission-form']) !!}


<div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12">
        <div class="panel panel-default">
            <div class="panel-heading">CMS Page</div>
            <div class="panel-body">
                <div class="form-group">
                    <label for="name">@lang('app.name')</label>
                    <input type="text" class="form-control" id="name"
                           name="page" readonly="readonly" placeholder="@lang('app.permission_name')" value="{{ $edit ? $page->page : old('name') }}">
                </div>
                <div class="form-group">
                    <label for="description">@lang('app.description')</label>
                    <textarea rows=15 name="description" id="description" class="form-control">{{ $edit ? $page->content : old('description') }}</textarea>
                </div>
                </div>
            </div>
        </div>
    </div>

<div class="row">
    <div class="col-md-2">
        <button type="submit" class="btn btn-primary">
            <i class="fa fa-save"></i>
              Update
        </button>
    </div>
</div>

@stop

resources/views/dashboard/cms/index.blade.php
@extends('dashboard.layouts.master')

@section('page-title', trans('app.permissions'))

@section('page-header')
    <h1>
      C M S Page
        <small>available CMS page list</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="{{ route('dashboard') }}"><i class="fa fa-dashboard"></i> @lang('app.home')</a></li>
        <li class="active"></li>
      </ol>
@endsection

@section('content')

@include('partials.messages')

<div class="box">
    <div class="box-header">
        <h3 class="box-title">CMS Page Lists</h3>
        <br><br>
      </div>
      <div class="box-body table-responsive no-padding" id="users-table-wrapper">
            <table class="table table-hover">
                <thead>
                    <th>#</th>
                    <th class="text-center">Page Name</th>
                    <th class="text-center">Page Updated On</th>
                    <th class="text-center">Edit</th>
                </thead>
                <tbody>
                    @if (count($pages))
                    @foreach($pages as $k=>$page)
                    <tr>
                        <td>{{ ++$k}}</td>
                        <td class="text-center">{{ $page->page }}</td>
                        <td class="text-center">{{ $page->updated_at }}</td>
                        <td class="text-center">
                            <a href="{{ route('dashboard.cms.edit', $page->id) }}" class="btn btn-primary btn-circle"
                                title="Edit Page" data-toggle="tooltip" data-placement="top">
                                <i class="glyphicon glyphicon-edit"></i>
                            </a>
                        </td>
                    </tr>
                    @endforeach
                    @else
                    <tr>
                        <td colspan="4"><em>@lang('app.no_records_found')</em></td>
                    </tr>
                    @endif
                </tbody>
            </table>
        </div>
  </div>



@stop